env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
builds:
  - id: seed
    main: main.go
    binary: seed
    env:
      - CGO_ENABLED=0
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .FullCommit }}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
dockers:
  - image_templates:
      - "docker.pkg.github.com/texanraj/websvrapp/seed:{{ .Version }}"
    binaries:
      - seed
    build_flag_templates:
      - "--label=org.label-schema.schema-version=1.0"
      - "--label=org.label-schema.version={{ .Version }}"
      - "--label=org.label-schema.name={{ .ProjectName }}"
      - "--label=org.label-schema.vcs=https://github.com/texanraj/websvrapp"
      - "--label=org.label-schema.vcs-ref={{ .FullCommit }}"
