name: Build WebSvrApp

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  release:
    name: Release
    runs-on: ubuntu-18.04
    steps:
      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Release snapshot
        uses: goreleaser/goreleaser-action@v1
        with:
          args: release --snapshot --skip-publish --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_REGISTRY_TOKEN }}
      - name: Loging to GitHub Package Registry
        run: |
          docker login -u ${{ secrets.GITHUB_REGISTRY_USER }} -p ${{ secrets.GITHUB_REGISTRY_TOKEN }} docker.pkg.github.com
      - name: Scan image for vulnerabilities
        uses: docker://docker.io/aquasec/trivy:0.2.1
        with:
          args: --cache-dir /var/lib/trivy docker.pkg.github.com/texanraj/websvrapp/websvrapp:${{ github.sha }}
